# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

import argparse
import os
import sys
import string
import json

# Search the test title in the record diction
# @param title: The test title you want to search.
# @param dict:  The diction to save all records.
def search(title, dict):
    if title in dict:
        return dict[title]
    else:
        return 'Not found!'

# The input file is generated by ftw_comparator.
parser = argparse.ArgumentParser()
parser.add_argument('--file', '-f', 
                    help = 'specify the json file generated by FTW Comparator', 
                    default = 'comp_output.json')                   
args=parser.parse_args()

try:
    json_file = open(args.file,'rb')
except IOError:
    sys.stderr.write('Cannot open the file ' + args.file + '\n')
    exit()

for line in json_file:
    log_dict = json.loads(line)
    
# Read request form command line until user input an empty request.
while True:
    title = raw_input('Input the test title:\n')
    print(title)
    if title == '':
        break
    print(search(title, log_dict))

